const vm = require('node:vm');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const records = new Map();
const users = new Map();
const deleted = Symbol('deleted');
const ref = key => ({ key, get: async () => ({exists:records.has(key), data:()=>records.get(key)}), set:async value=>records.set(key,value) });
let transactionTail = Promise.resolve();
const db = {collection: name => ({doc: id => ref(`${name}/${id}`)}),runTransaction: fn => { const next = transactionTail.then(() => fn({set:(r,v)=>records.set(r.key,v),get:r=>r.get(),create:(r,v)=>records.set(r.key,v),update:(r,v)=>{const data={...records.get(r.key),...v};for(const key in data)if(data[key]===deleted)delete data[key];records.set(r.key,data);}})); transactionTail = next.catch(() => {}); return next; }};
const auth = {createUser:async u=>{if([...users.values()].some(x=>x.email===u.email))throw Error('duplicate');users.set(u.uid,u);},deleteUser:async uid=>users.delete(uid)};
class HttpsError extends Error {constructor(code,message){super(message);this.code=code;}}
const admin = {initializeApp(){},firestore:()=>db,storage:()=>({bucket:()=>({})}),auth:()=>auth};
admin.firestore.Timestamp={fromMillis:ms=>({toMillis:()=>ms})};
admin.firestore.FieldValue={serverTimestamp:()=>0,delete:()=>deleted};
const exported={};
const context={require:name=>name==='firebase-admin'?admin:name==='firebase-functions/v2/https'?{onCall:(...args)=>args.at(-1),HttpsError}:name==='firebase-functions/params'?{defineSecret:()=>({})}:require(name),exports:exported,console};
vm.createContext(context);
vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../index.js'),'utf8'),context);
(async()=>{
 await assert.rejects(exported.createInvitation({}),{code:'permission-denied'});
 await assert.rejects(exported.getMatchup({}),{code:'unauthenticated'});
 await assert.rejects(exported.getMatchup({auth:{uid:'outsider',token:{}}}),{code:'permission-denied'});
 const adminRequest={auth:{uid:'owner',token:{admin:true}}};
 const {token}=await exported.createInvitation(adminRequest);
 const request={data:{token,email:'friend@example.com',password:'long-password-123'}};
 await exported.registerWithInvitation(request);
 assert.equal(users.size,1);assert.equal([...records.keys()].filter(k=>k.startsWith('members/')).length,1);
 await assert.rejects(exported.registerWithInvitation({...request,data:{...request.data,email:'cooldown@example.com'}}),{code:'resource-exhausted'});
 const inviteKey='invitations/'+require('node:crypto').createHash('sha256').update(token).digest('hex');
 records.get(inviteKey).nextAvailableAt={toMillis:()=>0};
 await exported.registerWithInvitation({data:{...request.data,email:'next@example.com'}});
 assert.equal(records.get(inviteKey).signupCount,2);
 assert.equal(users.size,2);
 await assert.rejects(exported.createInvitation({...adminRequest,data:{cooldownSeconds:0}}),{code:'invalid-argument'});
 const legacy=await exported.createInvitation(adminRequest);
 const legacyKey='invitations/'+require('node:crypto').createHash('sha256').update(legacy.token).digest('hex');
 delete records.get(legacyKey).reusable;
 await exported.registerWithInvitation({data:{...request.data,token:legacy.token,email:'legacy@example.com'}});
 await assert.rejects(exported.registerWithInvitation({data:{...request.data,token:legacy.token,email:'legacy2@example.com'}}),{code:'permission-denied'});
 const busy=await exported.createInvitation(adminRequest);
 const busyKey='invitations/'+require('node:crypto').createHash('sha256').update(busy.token).digest('hex');
 records.get(busyKey).reservedBy='other-request';
 await assert.rejects(exported.registerWithInvitation({data:{...request.data,token:busy.token,email:'busy@example.com'}}),{code:'resource-exhausted'});
 const expired=await exported.createInvitation(adminRequest);
 const hash=require('node:crypto').createHash('sha256').update(expired.token).digest('hex');
 records.get('invitations/'+hash).expiresAt={toMillis:()=>0};
 await assert.rejects(exported.registerWithInvitation({data:{...request.data,token:expired.token}}),{code:'permission-denied'});
 const duplicate=await exported.createInvitation(adminRequest);
 await assert.rejects(exported.registerWithInvitation({data:{...request.data,token:duplicate.token}}),{code:'failed-precondition'});
 await exported.registerWithInvitation({data:{...request.data,email:'second@example.com',token:duplicate.token}});
 assert.equal(users.size,4);
 records.set('stats/beerCounter',{count:4.4,totalAlcoholOz:2.64});
 const memberRequest={auth:{uid:[...users.keys()][0],token:{}}};
 await exported.addBeer(memberRequest);
 assert.equal(JSON.stringify(records.get('stats/beerCounter')),JSON.stringify({count:5}));
 await Promise.all(Array.from({length:20},()=>exported.addBeer(memberRequest)));
 assert.equal(records.get('stats/beerCounter').count,25);
 await assert.rejects(exported.addBeer({}),{code:'unauthenticated'});
 await assert.rejects(exported.addBeer({auth:{uid:'outsider',token:{}}}),{code:'permission-denied'});
 records.set('config/current',{week:1,spinLocked:true,weeklyPassword:'leaked-old-password'});
 records.set('config/private',{weeklyPassword:'private-password'});
 await assert.rejects(exported.verifyWeeklyPassword({...memberRequest,data:{password:'leaked-old-password'}}),{code:'permission-denied'});
 await exported.verifyWeeklyPassword({...memberRequest,data:{password:'private-password'}});
 for(const name of ['verifyWeeklyPassword','spinWheel','getUploadUrl'])await assert.rejects(exported[name]({}),{code:'unauthenticated'});
 console.log('Passed: admin-only invitations, nonmember denial, signup, shared link reuse after cooldown, cooldown denial, concurrent reservation denial, legacy single-use links, expired invitations, reservation release after failed signup, and member-only callable guards, whole-beer normalization, concurrent increments, and private wheel-password checks.');
})().catch(e=>{console.error(e);process.exitCode=1;});
